name: Publish Package

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
      

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: src

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Pack
        run: dotnet pack --configuration Release --output ./output

      - name: Publish to GitHub Packages
        run: dotnet nuget push ./output/*.nupkg --source github --api-key ${{ secrets.GITHUB_TOKEN }}
